minimumReleaseAge: 7200 # 5 days
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43800 # 1 month

minimumReleaseAgeExclude:
  - '@bart.sk-eshop/*'
trustPolicyExclude:
  - '@bart.sk-eshop/*'
allowBuilds:
  unrs-resolver: false
